name: NEW ZEALAND PRODUCTS
favicon: null
layout_spectrum: 0.06607
typography_spectrum: 0.44319
title: 'Personal Shopper '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000022'
    - '#00326e'
    - '#708dad'
    - '#c5b7c8'
    - '#f3f3f2'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
purpose: []
